name: spa
description: "A new Flutter project."

publish_to: "none"
version: 2.0.5+27

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  country_code_picker: ^3.0.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  elegant_notification: ^2.3.0
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.8
  flutter_image_compress: ^2.3.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  flag: ^7.0.0
  jumping_dot: ^0.0.7
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  html: ^0.15.4
  share_plus: ^10.0.2
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  logger: ^2.4.0
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/Screenshot_2023-11-21_213101-removebg-preview.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "Assets/Screenshot_2023-11-21_213101-removebg-preview.png"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/
