Map<String, String> drawer_Arabic = {
  "Choisir une langue": "اختيار لغة",
  "Votre nom": "اسمك",
  "Accueil": "الرئيسية",
  "Explore salon": "استكشاف الصالون",
  "Tout les salon": "جميع الصالونات",
  "Profile": "الملف الشخصي",
  "Favoris": "المفضلة",
  "Réservation": "الحجز",
  "Contactez-nous": "اتصل بنا",
  "Choisir language": "اختيار اللغة",
  "Déconnexion": "تسجيل الخروج",
  "Sélectionner une ville": "اختر المدينة",
  "Messagerie": "الرسائل ",
  "Anglais": "الإنجليزية",
  "Arabe": "العربية",
  "Français": "الفرنسية",
};

Map<String, String> drawer_English = {
  "Choisir une langue": "Choose a language",
  "Votre nom": "Your name",
  "Accueil": "Home",
  "Explore salon": "Explore salon",
  "Tout les salon": "All salons",
  "Profile": "Profile",
  "Favoris": "Favorites",
  "Réservation": "Booking",
  "Contactez-nous": "Contact us",
  "Choisir language": "Choose language",
  "Déconnexion": "Logout",
  "Sélectionner une ville": "Select City",
  "Messagerie": "Messaging",
  "Anglais": "English",
  "Arabe": "Arabic",
  "Français": "French",
};
