Map<String, String> home_Arabic = {
  "Recherche...": "البحث...",
  "Rechercher": "البحث",
  "Tout les salon": "جميع الصالونات",
  "Rechercher des salons...": 'البحث عن أماكن...',
  "Aucun salon disponible": "لا توجد صالونات متاحة",
  "Ouvert maintenant": "مفتوح الآن",
  "Tous les genres": "كل الأجناس",
  "Homme": "رجال",
  "Femme": "نساء",
  "Mixte": "مختلط",
  "Filtres": "تصفية",
  "Salons favoris": "الصالونات المفضلة",
  "Rechercher des salons": "البحث عن صالونات",
  "Réservations": "رقم الحجز",
  "Prix total: ": "السعر الإجمالي:  ",
  "Nom": "الاسم",
  "E-mail": "البريد الإلكتروني",
  "Message": "الرسالة",
  "Envoyer": "إرسال",
  "Informations de contact": "معلومات الاتصال",
  "Type": "النوع",
  "Aucun réservations disponible": "لا توجد حجوزات متاحة",
  "Vous n'avez aucune discussion disponible": "ليس لديك دردشات متاحة",
  "Service Client": "خدمة العملاء",
  "Ambiance": "أجواء",
  "Propreté": "نظافة",
  "Note Globale": "تقييم عام",
  "Votre commentaire...": "تعليقك...",
  "mâle": "ذكر",
  "Ouvert": "مفتوح",
  "Fermé": "مغلق",
  "Explorer le salon": "استكشاف الصالون",
};

Map<String, String> home_English = {
  "Recherche...": "Search...",
  "Rechercher": "Search",
  "Tout les salon": "All salons",
  "Rechercher des salons...": "Search places...",
  "Aucun salon disponible": "No available salons",
  "Ouvert maintenant": "Open now",
  "Tous les genres": "All genders",
  "Homme": "Men",
  "Femme": "Women",
  "Mixte": "Mixed",
  "Filtres": "Filters",
  "Salons favoris": "Favorite salons",
  "Rechercher des salons": "Search Salons",
  "Réservations": "Reservations",
  "Prix total: ": "Total Price:  ",
  "Nom": "Name",
  "E-mail": "Email",
  "Message": "Message",
  "Envoyer": "Send",
  "Informations de contact": "Contact Information",
  "Type": "Type",
  "Aucun réservations disponible": "No reservations available",
  "Vous n'avez aucune discussion disponible": "You have no chats available",
  "Service Client": "Customer Service",
  "Ambiance": "Ambiance",
  "Propreté": "Cleanliness",
  "Note Globale": "Overall Rating",
  "Votre commentaire...": "Your comment...",
  "female": "female",
  "Ouvert": "open",
  "mâle": "male",
  "Fermé": "Closed",
  "Explorer le salon": "Explore the lounge",
};
