Map<String, String> service_details_Arabic = {
  "Détails": "تفاصيل",
  "Services": "الخدمات",
  "Galerie": "المعرض",
  "Avis": "التقييمات",
  "Description": "الوصف",
  "Contactez-nous": "اتصل بنا",
  "Envoyer un message": "إرسال رسالة",
  "Liste de disponibilité": "قائمة التوفر",
  "Lundi": "الاثنين",
  "Mardi": "الثلاثاء",
  "Mercredi": "الأربعاء",
  "Jeudi": "الخميس",
  "Vendredi": "الجمعة",
  "Samedi": "السبت",
  "Dimanche": "الأحد",
  "localisation": "التوطين",
  "Liste des services": "قائمة الخدمات",
  "Contacter le salon": "الاتصال بالصالون",
  "Voir détails": "عرض التفاصيل",
  "Réserver": "احجز",
  "Note moyenne : ": "التقييم المتوسط: ",
  "Ouvert": "مفتوح",
  "Fermé": "مغلق",
  "Réserver maintenant": "احجز الآن",
  "Explorer le salon": "استكشاف الصالون",
  "Avis totaux": "إجمالي التقييمات",
  "Moyenne": "متوسط",
  "Ajoutez votre commentaire": "أضف تعليقك",
};

Map<String, String> service_details_English = {
  "Détails": "Details",
  "Services": "Services",
  "Galerie": "Gallery",
  "Avis": "Reviews",
  "Description": "Description",
  "Contactez-nous": "Contact Us",
  "Envoyer un message": "Send a Message",
  "Liste de disponibilité": "Availability List",
  "Lundi": "Monday",
  "Mardi": "Tuesday",
  "Mercredi": "Wednesday",
  "Jeudi": "Thursday",
  "Vendredi": "Friday",
  "Samedi": "Saturday",
  "Dimanche": "Sunday",
  "localisation": "localization",
  "Liste des services": "List service",
  "Contacter le salon": "Contact the salon",
  "Voir détails": "View details",
  "Réserver": "Reserve",
  "Note moyenne : ": "Average Rating : ",
  "Ouvert": "Open",
  "Fermé": "Closed",
  "Réserver maintenant": "Book now",
  "Explorer le salon": "Explore the salon",
  "Avis totaux": "Total Reviews",
  "Moyenne": "Average",
  "Ajoutez votre commentaire": "Add Your Comment",
};
